### ISSUE TITLE
Tree walk splitter can throw error getting the block links

### ISSUE THREAD

**Issue by vasco-santos** [alanshaw/carbites#2]
I got this error while splitting arbitrary large car Files (over 100mb)

```
RangeError: Too many properties to enumerate
      at Function.entries (<anonymous>)
      at links (/Users/vsantos/gh/nft.storage/node_modules/carbites/node_modules/multiformats/cjs/src/block.js:19:37)
      at links.next (<anonymous>)
      at TreewalkCarSplitter._cars (/Users/vsantos/gh/nft.storage/node_modules/carbites/cjs/lib/treewalk/splitter.js:94:22)
      at _cars.next (<anonymous>)
      at TreewalkCarSplitter._cars (/Users/vsantos/gh/nft.storage/node_modules/carbites/cjs/lib/treewalk/splitter.js:95:24)
      at _cars.next (<anonymous>)
      at TreewalkCarSplitter.cars (/Users/vsantos/gh/nft.storage/node_modules/carbites/cjs/lib/treewalk/splitter.js:54:22)
      at cars.next (<anonymous>)
```

**Comment by alanshaw** [comment]
According to https://stackoverflow.com/questions/34430182/too-many-properties-in-a-js-object the propery limit is 65,535. If you have an array with more than 65,535 CIDs then you'll hit this.

This could happen if you create a CBOR node with tons of children like https://github.com/alanshaw/carbites/blob/6f14737f77921fef0b4fbfc67bac6d7ea3fb0690/test/_helpers.js#L19 builds.

In practice IPFS will only create pb nodes with 174 children max, but `Block#links` should be updated to iterate over arrays instead of using `Object.entries`.
